version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "start"]
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    working_dir: /app
    environment:
      # Neo4j connection (using service names)
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=passwordseguro
      # Redis connection
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # JWT Security (change in production)
      - JWT_SECRET_KEY=dev_jwt_secret_key_change_in_production_123456
      - JWT_REFRESH_SECRET_KEY=dev_refresh_secret_key_change_in_production_789
      # Admin user
      - ADMIN_PASSWORD=Admin123!Dev
      - ADMIN_EMAIL=admin@logistics-dev.com
      # Environment
      - ENVIRONMENT=development
    depends_on:
      - neo4j
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes

  neo4j:
    image: neo4j:latest
    container_name: neo4j-gds
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/passwordseguro
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import

volumes: {}
