version: "3"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-gds
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/passwordseguro"
      NEO4J_PLUGINS: '["graph-data-science"]'
