version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    command: ["npm", "start"]
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:z
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    working_dir: /app
    depends_on:
      - neo4j
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data:z
    command: redis-server --appendonly yes

  neo4j:
    image: neo4j:latest
    container_name: neo4j-gds
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/passwordseguro
      - NEO4J_PLUGINS=["graph-data-science"]
    volumes:
      - ./neo4j/data:/data:z
      - ./neo4j/logs:/logs:z
      - ./neo4j/import:/import:z

volumes: {}
